### PR TITLE
Update connector.rb

### PR DESCRIPTION
**Pull request by sadfuzzy**
Otherwise can be nil and fails to form new Message

### CODE REVIEW

**Comment by sadfuzzy** [comment]
@lazyfrosch, plz merge

**Comment by lazyfrosch** [comment]
@sadfuzzy well, thanks for your work, I started this repo as a test bed, since the hipchat connector is no longer in a state which works with any other XMPP server.

But honestly I lost interest in chatbots for now, this repo never was in a usable state.

I suggest that you take it over, feel free to remove my name from it, or start fresh as a fork of the hipchat connector.

**Comment by sadfuzzy** [comment]
@lazyfrosch, ok! Thanks

**Comment by lazyfrosch** [comment]
@sadfuzzy shall I transfer the repo to you?

**Comment by sadfuzzy** [comment]
@lazyfrosch, would be great!

**Comment by lazyfrosch** [comment]
@sadfuzzy you would have to rename your fork before I can do that

**Comment by sadfuzzy** [comment]
done!

**Pull request merged**
